### ISSUE TITLE
Cannot browse some website

### ISSUE THREAD

**Issue by christopherwoo** [coljamkop/eww-layer#1]
when I visit this websize: ***https://docute.org/#/*** .
I got
> We're sorry but Docute doesn't work properly without JavaScript enabled. Please enable it to continue. 

How can I enable js?

**Comment by ckopsa** [comment]
Too my knowledge, eww doesn't do any JavaScript, which is a limitation of eww and not so much this layer.

I am pretty sure this will be an issue with most websites with client side rendering.

As far as what it would take to fix it, I think eww would have to have some engine that could process the javascript and render it in such a way that makes sense in emacs.
